# Generated by Django 5.1.1 on 2024-09-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleador',
            name='ProfesionABuscar',
        ),
        migrations.RemoveField(
            model_name='trabajo',
            name='codigo',
        ),
    ]
